export const theme = {
  colors: {
    primary: '#D31145',
    secondary: '#424242',
    dark: '#292825',
    lightGray: '#F2F2F2',
    gray: '#d8d8d8',
    darkGray: '#a5a5a6',
    iconForm: '#596C80',
    darkYellow: '#DBB680',
    lightYellow: '#FAF9F5',
    darkBgForm: '#E8E8E8',
    brown: '#695556',
    danger: '#D31145',
    complete: '#0086C8',
    approved: '#9DC869',
    darkBlueGray: '#596C80',
    white: '#fff',
    black: '#000',
  },
  default: {
    component: {
      button: {
        bg: 'primary',
        color: 'white',
        rounded: true,
        padding: '12px 32px',
        radius: '4px',
        fluid: false,
        variant: 'solid',
        fontFamily: 'AIARegular',
      },
      input: {
        bg: 'lightGray',
        color: 'secondary',
        padding: '12px 16px',
        radius: '15px',
        rounded: false,
        fluid: false,
        fontFamily: 'AIARegular',
        variant: 'solid',
        borderColor: 'primary',
        focusBorderColor: 'primary',
        paddingleftElement: '36px',
        paddingRightElement: '36px',
      },
    },
  },
}
