import React from 'react'
import { mergeDeep } from '../utils'

import { Icon } from './icon'

export const theme = {
  colors: {
    primary: '#D31145',
    secondary: '#424242',
    dark: '#292825',
    lightGray: '#E8E8E8',
    lightGray2: '#F2F2F2',
    gray: '#d8d8d8',
    darkGray: '#a5a5a6',
    iconForm: '#596C80',
    darkYellow: '#DBB680',
    lightYellow: '#FAF9F5',
    darkBgForm: '#E8E8E8',
    brown: '#695556',
    danger: '#D31145',
    complete: '#0086C8',
    approved: '#9DC869',
    darkBlueGray: '#596C80',
    white: '#fff',
    black: '#000',
  },
  fontFamily: {
    regular: 'AIARegular',
    medium: 'AIAMedium',
    condensed: 'AIACondensed',
    condensedMedium: 'AIACondensedMedium',
  },
  fontSize: {
    xs: '1rem',
    sm: '1.2rem',
    md: '1.4rem',
    lg: '2rem',
  },
  fontWeight: {
    normal: 'normal',
    'semi-bold': 'semi-bold',
    bold: 'bold',
  },
  radius: {
    sm: '4px',
    md: '8px',
    lg: '15px',
  },
  default: {
    component: {
      accordion: {
        wrapper: {
          arrowPosition: 'right',
          fontFamily: 'regular',
          fontSize: 'md',
          fontWeight: 'normal',
          width: '600px',
          fluid: false,
          allowToggle: false,
          allowMultiple: false,
        },
        item: {},
        header: {
          padding: '1rem',
          borderColor: 'lightGray',
          fontFamily: 'medium',
          fontSize: 'md',
          fontWeight: 'normal',
        },
        content: {
          padding: '1rem',
          maxHeight: '500px',
          color: 'secondary',
        },
      },
      button: {
        bg: 'primary',
        color: 'white',
        rounded: true,
        padding: '0.8em 2em',
        radius: 'sm',
        fluid: false,
        variant: 'solid',
        fontFamily: 'regular',
        fontSize: 'md',
        fontWeight: 'normal',
      },
      contactInput: {
        bg: 'lightGray',
        color: 'secondary',
        padding: '0.7rem 1.6rem',
        width: '335px',
        height: '40px',
        radius: 'lg',
        rounded: false,
        fluid: false,
        fontFamily: 'regular',
        fontSize: 'md',
        fontWeight: 'normal',
        variant: 'solid',
        borderColor: 'primary',
        focusBorderColor: 'primary',
        separatorColor: 'rgba(0,0,0,0.3)',
        supportedCode: [
          { value: '+65', name: '+65' },
          { value: '+62', name: '+62' },
          { value: '+60', name: '+60' },
        ],
      },
      datePicker: {
        bg: 'lightGray',
        color: 'secondary',
        padding: '1.2rem 1.6rem',
        radius: 'lg',
        rounded: false,
        fluid: false,
        width: '335px',
        height: '40px',
        fontFamily: 'regular',
        fontSize: 'md',
        fontWeight: 'normal',
        variant: 'solid',
        borderColor: 'primary',
        focusBorderColor: 'primary',
        rightElement: <Icon name='calendar' size='1.3em' />,
        paddingLeftElement: '3.6rem',
        paddingRightElement: '3.6rem',
        dateFormat: 'DD/MM/YYYY',
        calendarProps: {
          wrapperProps: {
            fontFamily: 'regular',
            fontSize: 'md',
            fontWeight: 'normal',
          },
          yearProps: {
            fontFamily: 'medium',
            fontSize: 'md',
            fontWeight: 'normal',
          },
          monthProps: {
            fontFamily: 'medium',
            fontSize: 'md',
            fontWeight: 'normal',
          },
          dayProps: {
            activeBg: 'primary',
            activeColor: 'white',
          },
          dateInputProps: {
            borderColor: 'primary',
          },
        },
      },
      divider: {
        bg: 'gray',
        marginBlock: '10px',
        fontFamily: 'regular',
        fontSize: 'md',
        fontWeight: 'normal',
        textPaddingInline: '20px',
        orientation: 'horizontal',
      },
      input: {
        bg: 'lightGray',
        color: 'secondary',
        padding: '1.2rem 1.6rem',
        radius: 'lg',
        rounded: false,
        fluid: false,
        width: '335px',
        fontFamily: 'regular',
        fontSize: 'md',
        fontWeight: 'normal',
        variant: 'solid',
        borderColor: 'primary',
        focusBorderColor: 'primary',
        paddingLeftElement: '3.6rem',
        paddingRightElement: '3.6rem',
      },
      checkbox: {
        activeColor: 'primary',
        borderColor: 'primary',
        color: 'secondary',
        radius: 'sm',
        fontFamily: 'regular',
        fontSize: 'md',
        fontWeight: 'normal',
        width: 'auto',
        height: 'auto',
        fluid: false,
      },
      radio: {
        activeColor: 'primary',
        borderColor: 'primary',
        color: 'secondary',
        radius: 'sm',
        fontFamily: 'regular',
        fontSize: 'md',
        fontWeight: 'normal',
        variant: 'circular',
      },
      radioButton: {
        bg: 'primary',
        activeBGColor: 'secondary',
        activeTextColor: 'white',
        color: 'white',
        radius: 'lg',
        variant: 'outline',
        fontFamily: 'medium',
        fontSize: 'md',
        fontWeight: 'normal',
        buttonType: 'default',
        padding: '0.8em 2em',
        fluid: false,
        width: '150px',
        height: '40px',
        iconSpacing: '30px',
        size: '140px',
      },
      tag: {
        bg: 'primary',
        color: 'white',
        padding: '0.3rem 1rem',
        variant: 'solid',
        radius: 'sm',
        fontFamily: 'regular',
        fontSize: 'sm',
        fontWeight: 'normal',
        textTransform: 'uppercase',
      },
      modal: {
        wrapper: {
          fontFamily: 'regular',
          fontSize: 'md',
          fontWeight: 'normal',
          bg: 'white',
          radius: 'lg',
          width: '450px',
        },
        close: {
          position: 'right',
        },
        content: {
          padding: '3rem',
          alignment: 'center',
        },
        header: {
          bg: 'primary',
          color: 'white',
          padding: '2rem',
          fontFamily: 'medium',
          fontSize: 'md',
          fontWeight: 'normal',
          height: '90px',
          iconWrapperProps: {
            bg: 'white',
            boxShadow: 'rgb(170 8 54 / 32%) 2px 0px 10px 0px',
            padding: '1.5rem',
            color: 'primary',
          },
        },
        title: {
          margin: '0 0 20px 0',
          fontFamily: 'medium',
          fontSize: 'md',
          fontWeight: 'normal',
        },
        body: {
          color: 'secondary',
          margin: '0 0 20px 0',
          fontFamily: 'regular',
          fontSize: 'md',
          fontWeight: 'normal',
        },
        close: {
          bg: 'transparent',
          color: 'white',
          radius: 'sm',
        },
        actions: {
          spacing: '10px',
          alignment: 'center',
        },
      },
      radioGroup: {
        wrapper: {
          direction: 'column',
          gap: '10px',
        },
        radio: {
          activeColor: 'primary',
          borderColor: 'primary',
          color: 'secondary',
          radius: 'sm',
          fontFamily: 'regular',
          fontSize: 'md',
          fontWeight: 'normal',
          variant: 'circular',
        },
        radioButton: {
          width: '100%',
        },
      },
      textarea: {
        bg: 'lightGray',
        color: 'secondary',
        padding: '0.6rem 1.6rem',
        radius: 'lg',
        rounded: false,
        fluid: false,
        fontFamily: 'regular',
        fontSize: 'md',
        fontWeight: 'normal',
        variant: 'solid',
        borderColor: 'primary',
        focusBorderColor: 'primary',
        rows: 5,
        width: '335px',
        resize: 'none',
      },
      tooltip: {
        fontFamily: 'regular',
        fontSize: 'md',
        fontWeight: 'normal',
        placement: 'top',
        padding: '1rem',
        radius: 'sm',
        width: '200px',
        height: 'auto',
        bg: 'secondary',
        color: 'white',
        hasArrow: true,
      },
      select: {
        fluid: false,
        width: '335px',
        height: '40px',
        padding: '1.2rem 1.2rem 1.2rem 1.6rem',
        rounded: false,
        radius: 'lg',
        fontFamily: 'regular',
        fontSize: 'md',
        fontWeight: 'normal',
        icon: <Icon name='down' size='m' />,
        bg: 'lightGray',
        color: 'secondary',
        borderColor: 'primary',
        focusBorderColor: 'primary',
        placeholderColor: 'darkGray',
        variant: 'solid',
        searchable: false,
      },
      table: {
        wrapper: {
          width: '100%',
          variant: 'striped',
          borderSpacing: 0,
        },
        header: {
          padding: '1.2rem 1.5rem 1.4rem 1.5rem',
          bg: 'lightGray',
          fontFamily: 'medium',
          fontSize: 'md',
          fontWeight: 'normal',
          borer: 0,
          cursor: 'auto',
          alignment: 'left',
        },
        row: {
          stripeColor: 'lightGray2',
        },
        data: {
          padding: '1.1rem 1.5rem',
          border: '1px solid',
          borderColor: 'lightGray2',
          fontFamily: 'regular',
          fontSize: 'md',
          fontWeight: 'normal',
          cursor: 'auto',
          lineHeight: '18px',
        },
      },
      unitNumber: {
        bg: 'lightGray',
        color: 'secondary',
        padding: '0.7rem 1.6rem',
        width: '335px',
        height: '40px',
        radius: 'lg',
        rounded: false,
        fluid: false,
        fontFamily: 'regular',
        fontSize: 'md',
        fontWeight: 'normal',
        variant: 'solid',
        borderColor: 'primary',
        focusBorderColor: 'primary',
        alignment: 'center',
      },
    },
  },
}

export const extendTheme = (newTheme) => {
  return mergeDeep(theme, newTheme)
}
