import React from 'react'
import { Icon } from './icon'

export const theme = {
  colors: {
    primary: '#D31145',
    secondary: '#424242',
    dark: '#292825',
    lightGray: '#E8E8E8',
    lightGray2: '#F2F2F2',
    gray: '#d8d8d8',
    darkGray: '#a5a5a6',
    iconForm: '#596C80',
    darkYellow: '#DBB680',
    lightYellow: '#FAF9F5',
    darkBgForm: '#E8E8E8',
    brown: '#695556',
    danger: '#D31145',
    complete: '#0086C8',
    approved: '#9DC869',
    darkBlueGray: '#596C80',
    white: '#fff',
    black: '#000',
  },
  radius: {
    sm: '4px',
    md: '8px',
    lg: '12px',
  },
  default: {
    component: {
      accordion: {
        wrapper: {
          arrowPosition: 'right',
          fontFamily: 'AIARegular',
          fontSize: '1.4rem',
          fontWeight: 'normal',
          width: '600px',
          fluid: false,
          allowToggle: false,
          allowMultiple: false,
        },
        item: {},
        header: {
          padding: '10px',
          borderColor: 'lightGray',
          fontFamily: 'AIAMedium',
          fontSize: '1.4rem',
          fontWeight: 'normal',
        },
        content: {
          padding: '10px',
          maxHeight: '500px',
          color: 'secondary',
        },
      },
      button: {
        bg: 'primary',
        color: 'white',
        rounded: true,
        padding: '0.8em 2em',
        radius: '4px',
        fluid: false,
        variant: 'solid',
        fontFamily: 'AIARegular',
        fontSize: '1.4rem',
        fontWeight: 'normal',
      },
      contactInput: {
        bg: 'lightGray',
        color: 'secondary',
        padding: '7px 16px',
        width: '335px',
        height: '40px',
        radius: '15px',
        rounded: false,
        fluid: false,
        fontFamily: 'AIARegular',
        fontSize: '1.4rem',
        fontWeight: '400',
        variant: 'solid',
        borderColor: 'primary',
        focusBorderColor: 'primary',
        separatorColor: 'rgba(0,0,0,0.3)',
        supportedCode: [
          { value: '+65', name: '+65' },
          { value: '+62', name: '+62' },
          { value: '+60', name: '+60' },
        ],
      },
      datePicker: {
        bg: 'lightGray',
        color: 'secondary',
        padding: '12px 16px',
        radius: '15px',
        rounded: false,
        fluid: false,
        width: '335px',
        fontFamily: 'AIARegular',
        fontSize: '1.4rem',
        fontWeight: 'normal',
        variant: 'solid',
        borderColor: 'primary',
        focusBorderColor: 'primary',
        rightElement: <Icon name='calendar' size='1.3em' />,
        paddingLeftElement: '36px',
        paddingRightElement: '36px',
        dateFormat: 'DD/MM/YYYY',
        calendarProps: {
          wrapperProps: {
            fontFamily: 'AIARegular',
            fontSize: '1.4rem',
            fontWeight: 'normal',
          },
          yearProps: {
            fontFamily: 'AIAMedium',
            fontSize: '1.4rem',
            fontWeight: 'normal',
          },
          monthProps: {
            fontFamily: 'AIAMedium',
            fontSize: '1.4rem',
            fontWeight: 'normal',
          },
          dayProps: {
            activeBg: 'primary',
            activeColor: 'white',
          },
        },
      },
      divider: {
        bg: 'gray',
        marginBlock: '10px',
        fontFamily: 'AIARegular',
        fontWeight: 'normal',
        fontSize: '1.4rem',
        textPaddingInline: '20px',
        orientation: 'horizontal',
      },
      input: {
        bg: 'lightGray',
        color: 'secondary',
        padding: '12px 16px',
        radius: '15px',
        rounded: false,
        fluid: false,
        width: '335px',
        fontFamily: 'AIARegular',
        fontSize: '1.4rem',
        fontWeight: 'normal',
        variant: 'solid',
        borderColor: 'primary',
        focusBorderColor: 'primary',
        paddingLeftElement: '36px',
        paddingRightElement: '36px',
      },
      checkbox: {
        activeColor: 'primary',
        borderColor: 'primary',
        color: 'secondary',
        radius: '4px',
        fontSize: '1.4rem',
        fontFamily: 'AIARegular',
        fontWeight: 'normal',
        width: 'auto',
        height: 'auto',
        fluid: false,
      },
      radio: {
        activeColor: 'primary',
        borderColor: 'primary',
        color: 'secondary',
        radius: '4px',
        fontSize: '1.4rem',
        fontFamily: 'AIARegular',
        fontWeight: 'normal',
        variant: 'circular',
      },
      radioButton: {
        bg: 'primary',
        activeBGColor: 'secondary',
        activeTextColor: 'white',
        color: 'white',
        radius: '15px',
        variant: 'outline',
        fontSize: '1.4rem',
        fontFamily: 'AIAMedium',
        fontWeight: 'normal',
        buttonType: 'default',
        padding: '0.8em 2em',
        fluid: false,
        width: '150px',
        height: '40px',
        iconSpacing: '30px',
        size: '140px',
      },
      tag: {
        bg: 'primary',
        color: 'white',
        padding: '3px 10px',
        variant: 'solid',
        radius: '4px',
        fontSize: '1.4rem',
        fontFamily: 'AIAMedium',
        fontWeight: 'bold',
        textTransform: 'uppercase',
      },
      modal: {
        wrapper: {
          fontFamily: 'AIARegular',
          bg: 'white',
          radius: '15px',
          width: '450px',
        },
        close: {
          position: 'right',
        },
        content: {
          padding: '30px',
          alignment: 'center',
        },
        header: {
          bgImage:
            'linear-gradient(to right, rgb(232, 73, 116) 0%, rgb(205, 73, 96) 52%, rgb(193, 55, 91) 100%)',
          color: 'white',
          padding: '20px',
          fontFamily: 'AIAMedium',
          fontSize: '1.4rem',
          fontWeight: 'normal',
          iconWrapperProps: {
            bg: 'white',
            boxShadow: 'rgb(170 8 54 / 32%) 2px 0px 10px 0px',
            padding: '15px',
            color: 'primary',
          },
        },
        title: {
          margin: '0 0 20px 0',
          fontSize: '1.5rem',
          fontFamily: 'AIAMedium',
          fontWeight: 'normal',
        },
        body: {
          color: 'secondary',
          margin: '0 0 20px 0',
          fontSize: '1.5rem',
          fontFamily: 'AIARegular',
          fontWeight: 'normal',
        },
        close: {
          bg: 'transparent',
          color: 'white',
          radius: '4px',
        },
        actions: {
          spacing: '10px',
          alignment: 'center',
        },
      },
      radioGroup: {
        wrapper: {
          direction: 'column',
          gap: '10px',
        },
        radio: {
          activeColor: 'primary',
          borderColor: 'primary',
          color: 'secondary',
          radius: '4px',
          fontSize: '1.4rem',
          fontFamily: 'AIARegular',
          fontWeight: 'normal',
          variant: 'circular',
        },
      },
      textarea: {
        bg: 'lightGray',
        color: 'secondary',
        padding: '6px 16px',
        radius: '15px',
        rounded: false,
        fluid: false,
        fontFamily: 'AIARegular',
        fontSize: '1.4rem',
        fontWeight: 'normal',
        variant: 'solid',
        borderColor: 'primary',
        focusBorderColor: 'primary',
        rows: 5,
        width: '335px',
        resize: 'none',
      },
      tooltip: {
        fontFamily: 'AIARegular',
        fontSize: '1.4rem',
        fontWeight: 'normal',
        placement: 'top',
        padding: '10px',
        radius: '4px',
        width: '200px',
        height: 'auto',
        bg: 'secondary',
        color: 'white',
        hasArrow: true,
      },
      select: {
        fluid: false,
        width: '335px',
        height: '40px',
        padding: '10px 16px',
        rounded: false,
        radius: '15px',
        fontFamily: 'AIARegular',
        fontWeight: 'normal',
        fontSize: '1.4rem',
        icon: <Icon name='down' size='m' />,
        bg: 'lightGray',
        color: 'secondary',
        borderColor: 'primary',
        focusBorderColor: 'primary',
        placeholderColor: 'darkGray',
        variant: 'solid',
        searchable: false,
      },
      table: {
        wrapper: {
          width: '100%',
          variant: 'striped',
          borderSpacing: 0,
        },
        header: {
          padding: '12px 15px 14px 15px',
          bg: 'lightGray',
          fontFamily: 'AIAMedium',
          fontSize: '1.4rem',
          fontWeight: 'normal',
          borer: 0,
          cursor: 'auto',
          alignment: 'left',
        },
        row: {
          stripeColor: 'lightGray2',
        },
        data: {
          padding: '11px 15px',
          border: '1px solid',
          borderColor: 'lightGray2',
          fontFamily: 'AIARegular',
          fontSize: '1.4rem',
          fontWeight: 'normal',
          cursor: 'auto',
          lineHeight: '18px',
        },
      },
      unitNumber: {
        bg: 'lightGray',
        color: 'secondary',
        padding: '7px 16px',
        width: '335px',
        height: '40px',
        radius: '15px',
        rounded: false,
        fluid: false,
        fontFamily: 'AIARegular',
        fontSize: '1.4rem',
        fontWeight: 'normal',
        variant: 'solid',
        borderColor: 'primary',
        focusBorderColor: 'primary',
        alignment: 'center',
      },
    },
  },
}
